DROP PROCEDURE create_store;
DROP TABLE IF EXISTS producttag;
DROP TABLE IF EXISTS productatstore;
DROP TABLE IF EXISTS storetag;
DROP TABLE IF EXISTS appuserrole;
DROP TABLE IF EXISTS pricereview;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS appuser;

